### ISSUE TITLE
Only EmojiOne on OnePlus 3T

### ISSUE THREAD

**Issue by doktormerlin** [CzBiX/Telegram-Xposed#2]
There seems to be an issue where the emoji doesn't get updated correctly.

On my OP3T ever since installing ReEmoji there are only EmojiOne emoji, even though default was NoTo. Changing the settings doesn't do anything in Telegram, still only EmojiOne occurs.

**Comment by CzBiX** [comment]
My module doesn't support EmojiOne. You got the wrong place.
