### ISSUE TITLE
Oreo emojis

### ISSUE THREAD

**Issue by Joseahfer** [CzBiX/Telegram-Xposed#3]
Hello,
Would it be possible to create a separate module with Oreo emojis?
I'm currently using this module with Xposed Framework for Nougat and works fine.

Regards,
Jose.

**Comment by Joseahfer** [comment]
Hello,
Just discovered the version without integrated font, works as well with Xposed for Nougat and add the Oreo emojis (because I have it in my phone).

Regards,
Jose.

**Comment by CzBiX** [comment]
I personally do not like the new look of Google emoji.

But I'm still glad you solved the problem.
